/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCompleteRouteImport } from './routes/api/complete'
import { Route as ApiSessionsIndexRouteImport } from './routes/api/sessions/index'
import { Route as ApiHintIndexRouteImport } from './routes/api/hint/index'
import { Route as ApiCheckpointsIndexRouteImport } from './routes/api/checkpoints/index'
import { Route as ApiSessionsCodeRouteImport } from './routes/api/sessions/$code'
import { Route as ApiReportSessionIdRouteImport } from './routes/api/report/$sessionId'
import { Route as ApiCompletionsTeamIdRouteImport } from './routes/api/completions/$teamId'
import { Route as ApiCheckpointsIdRouteImport } from './routes/api/checkpoints/$id'
import { Route as ApiTaskCheckpointIdTeamIdRouteImport } from './routes/api/task/$checkpointId/$teamId'
import { Route as ApiSessionsIdIdRouteImport } from './routes/api/sessions/id/$id'
import { Route as ApiSessionsIdStatusRouteImport } from './routes/api/sessions/$id/status'
import { Route as ApiSessionsIdQrRouteImport } from './routes/api/sessions/$id/qr'
import { Route as ApiSessionsCodeJoinRouteImport } from './routes/api/sessions/$code/join'
import { Route as ApiCheckpointsSessionSessionIdRouteImport } from './routes/api/checkpoints/session/$sessionId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompleteRoute = ApiCompleteRouteImport.update({
  id: '/api/complete',
  path: '/api/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIndexRoute = ApiSessionsIndexRouteImport.update({
  id: '/api/sessions/',
  path: '/api/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHintIndexRoute = ApiHintIndexRouteImport.update({
  id: '/api/hint/',
  path: '/api/hint/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckpointsIndexRoute = ApiCheckpointsIndexRouteImport.update({
  id: '/api/checkpoints/',
  path: '/api/checkpoints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsCodeRoute = ApiSessionsCodeRouteImport.update({
  id: '/api/sessions/$code',
  path: '/api/sessions/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportSessionIdRoute = ApiReportSessionIdRouteImport.update({
  id: '/api/report/$sessionId',
  path: '/api/report/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompletionsTeamIdRoute = ApiCompletionsTeamIdRouteImport.update({
  id: '/api/completions/$teamId',
  path: '/api/completions/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckpointsIdRoute = ApiCheckpointsIdRouteImport.update({
  id: '/api/checkpoints/$id',
  path: '/api/checkpoints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskCheckpointIdTeamIdRoute =
  ApiTaskCheckpointIdTeamIdRouteImport.update({
    id: '/api/task/$checkpointId/$teamId',
    path: '/api/task/$checkpointId/$teamId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsIdIdRoute = ApiSessionsIdIdRouteImport.update({
  id: '/api/sessions/id/$id',
  path: '/api/sessions/id/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIdStatusRoute = ApiSessionsIdStatusRouteImport.update({
  id: '/api/sessions/$id/status',
  path: '/api/sessions/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIdQrRoute = ApiSessionsIdQrRouteImport.update({
  id: '/api/sessions/$id/qr',
  path: '/api/sessions/$id/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsCodeJoinRoute = ApiSessionsCodeJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ApiSessionsCodeRoute,
} as any)
const ApiCheckpointsSessionSessionIdRoute =
  ApiCheckpointsSessionSessionIdRouteImport.update({
    id: '/api/checkpoints/session/$sessionId',
    path: '/api/checkpoints/session/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/complete': typeof ApiCompleteRoute
  '/api/checkpoints/$id': typeof ApiCheckpointsIdRoute
  '/api/completions/$teamId': typeof ApiCompletionsTeamIdRoute
  '/api/report/$sessionId': typeof ApiReportSessionIdRoute
  '/api/sessions/$code': typeof ApiSessionsCodeRouteWithChildren
  '/api/checkpoints/': typeof ApiCheckpointsIndexRoute
  '/api/hint/': typeof ApiHintIndexRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/api/checkpoints/session/$sessionId': typeof ApiCheckpointsSessionSessionIdRoute
  '/api/sessions/$code/join': typeof ApiSessionsCodeJoinRoute
  '/api/sessions/$id/qr': typeof ApiSessionsIdQrRoute
  '/api/sessions/$id/status': typeof ApiSessionsIdStatusRoute
  '/api/sessions/id/$id': typeof ApiSessionsIdIdRoute
  '/api/task/$checkpointId/$teamId': typeof ApiTaskCheckpointIdTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/complete': typeof ApiCompleteRoute
  '/api/checkpoints/$id': typeof ApiCheckpointsIdRoute
  '/api/completions/$teamId': typeof ApiCompletionsTeamIdRoute
  '/api/report/$sessionId': typeof ApiReportSessionIdRoute
  '/api/sessions/$code': typeof ApiSessionsCodeRouteWithChildren
  '/api/checkpoints': typeof ApiCheckpointsIndexRoute
  '/api/hint': typeof ApiHintIndexRoute
  '/api/sessions': typeof ApiSessionsIndexRoute
  '/api/checkpoints/session/$sessionId': typeof ApiCheckpointsSessionSessionIdRoute
  '/api/sessions/$code/join': typeof ApiSessionsCodeJoinRoute
  '/api/sessions/$id/qr': typeof ApiSessionsIdQrRoute
  '/api/sessions/$id/status': typeof ApiSessionsIdStatusRoute
  '/api/sessions/id/$id': typeof ApiSessionsIdIdRoute
  '/api/task/$checkpointId/$teamId': typeof ApiTaskCheckpointIdTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/complete': typeof ApiCompleteRoute
  '/api/checkpoints/$id': typeof ApiCheckpointsIdRoute
  '/api/completions/$teamId': typeof ApiCompletionsTeamIdRoute
  '/api/report/$sessionId': typeof ApiReportSessionIdRoute
  '/api/sessions/$code': typeof ApiSessionsCodeRouteWithChildren
  '/api/checkpoints/': typeof ApiCheckpointsIndexRoute
  '/api/hint/': typeof ApiHintIndexRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/api/checkpoints/session/$sessionId': typeof ApiCheckpointsSessionSessionIdRoute
  '/api/sessions/$code/join': typeof ApiSessionsCodeJoinRoute
  '/api/sessions/$id/qr': typeof ApiSessionsIdQrRoute
  '/api/sessions/$id/status': typeof ApiSessionsIdStatusRoute
  '/api/sessions/id/$id': typeof ApiSessionsIdIdRoute
  '/api/task/$checkpointId/$teamId': typeof ApiTaskCheckpointIdTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/complete'
    | '/api/checkpoints/$id'
    | '/api/completions/$teamId'
    | '/api/report/$sessionId'
    | '/api/sessions/$code'
    | '/api/checkpoints/'
    | '/api/hint/'
    | '/api/sessions/'
    | '/api/checkpoints/session/$sessionId'
    | '/api/sessions/$code/join'
    | '/api/sessions/$id/qr'
    | '/api/sessions/$id/status'
    | '/api/sessions/id/$id'
    | '/api/task/$checkpointId/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/complete'
    | '/api/checkpoints/$id'
    | '/api/completions/$teamId'
    | '/api/report/$sessionId'
    | '/api/sessions/$code'
    | '/api/checkpoints'
    | '/api/hint'
    | '/api/sessions'
    | '/api/checkpoints/session/$sessionId'
    | '/api/sessions/$code/join'
    | '/api/sessions/$id/qr'
    | '/api/sessions/$id/status'
    | '/api/sessions/id/$id'
    | '/api/task/$checkpointId/$teamId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/complete'
    | '/api/checkpoints/$id'
    | '/api/completions/$teamId'
    | '/api/report/$sessionId'
    | '/api/sessions/$code'
    | '/api/checkpoints/'
    | '/api/hint/'
    | '/api/sessions/'
    | '/api/checkpoints/session/$sessionId'
    | '/api/sessions/$code/join'
    | '/api/sessions/$id/qr'
    | '/api/sessions/$id/status'
    | '/api/sessions/id/$id'
    | '/api/task/$checkpointId/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiCompleteRoute: typeof ApiCompleteRoute
  ApiCheckpointsIdRoute: typeof ApiCheckpointsIdRoute
  ApiCompletionsTeamIdRoute: typeof ApiCompletionsTeamIdRoute
  ApiReportSessionIdRoute: typeof ApiReportSessionIdRoute
  ApiSessionsCodeRoute: typeof ApiSessionsCodeRouteWithChildren
  ApiCheckpointsIndexRoute: typeof ApiCheckpointsIndexRoute
  ApiHintIndexRoute: typeof ApiHintIndexRoute
  ApiSessionsIndexRoute: typeof ApiSessionsIndexRoute
  ApiCheckpointsSessionSessionIdRoute: typeof ApiCheckpointsSessionSessionIdRoute
  ApiSessionsIdQrRoute: typeof ApiSessionsIdQrRoute
  ApiSessionsIdStatusRoute: typeof ApiSessionsIdStatusRoute
  ApiSessionsIdIdRoute: typeof ApiSessionsIdIdRoute
  ApiTaskCheckpointIdTeamIdRoute: typeof ApiTaskCheckpointIdTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complete': {
      id: '/api/complete'
      path: '/api/complete'
      fullPath: '/api/complete'
      preLoaderRoute: typeof ApiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/': {
      id: '/api/sessions/'
      path: '/api/sessions'
      fullPath: '/api/sessions/'
      preLoaderRoute: typeof ApiSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hint/': {
      id: '/api/hint/'
      path: '/api/hint'
      fullPath: '/api/hint/'
      preLoaderRoute: typeof ApiHintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkpoints/': {
      id: '/api/checkpoints/'
      path: '/api/checkpoints'
      fullPath: '/api/checkpoints/'
      preLoaderRoute: typeof ApiCheckpointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$code': {
      id: '/api/sessions/$code'
      path: '/api/sessions/$code'
      fullPath: '/api/sessions/$code'
      preLoaderRoute: typeof ApiSessionsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report/$sessionId': {
      id: '/api/report/$sessionId'
      path: '/api/report/$sessionId'
      fullPath: '/api/report/$sessionId'
      preLoaderRoute: typeof ApiReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/completions/$teamId': {
      id: '/api/completions/$teamId'
      path: '/api/completions/$teamId'
      fullPath: '/api/completions/$teamId'
      preLoaderRoute: typeof ApiCompletionsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkpoints/$id': {
      id: '/api/checkpoints/$id'
      path: '/api/checkpoints/$id'
      fullPath: '/api/checkpoints/$id'
      preLoaderRoute: typeof ApiCheckpointsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task/$checkpointId/$teamId': {
      id: '/api/task/$checkpointId/$teamId'
      path: '/api/task/$checkpointId/$teamId'
      fullPath: '/api/task/$checkpointId/$teamId'
      preLoaderRoute: typeof ApiTaskCheckpointIdTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/id/$id': {
      id: '/api/sessions/id/$id'
      path: '/api/sessions/id/$id'
      fullPath: '/api/sessions/id/$id'
      preLoaderRoute: typeof ApiSessionsIdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id/status': {
      id: '/api/sessions/$id/status'
      path: '/api/sessions/$id/status'
      fullPath: '/api/sessions/$id/status'
      preLoaderRoute: typeof ApiSessionsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$id/qr': {
      id: '/api/sessions/$id/qr'
      path: '/api/sessions/$id/qr'
      fullPath: '/api/sessions/$id/qr'
      preLoaderRoute: typeof ApiSessionsIdQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$code/join': {
      id: '/api/sessions/$code/join'
      path: '/join'
      fullPath: '/api/sessions/$code/join'
      preLoaderRoute: typeof ApiSessionsCodeJoinRouteImport
      parentRoute: typeof ApiSessionsCodeRoute
    }
    '/api/checkpoints/session/$sessionId': {
      id: '/api/checkpoints/session/$sessionId'
      path: '/api/checkpoints/session/$sessionId'
      fullPath: '/api/checkpoints/session/$sessionId'
      preLoaderRoute: typeof ApiCheckpointsSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSessionsCodeRouteChildren {
  ApiSessionsCodeJoinRoute: typeof ApiSessionsCodeJoinRoute
}

const ApiSessionsCodeRouteChildren: ApiSessionsCodeRouteChildren = {
  ApiSessionsCodeJoinRoute: ApiSessionsCodeJoinRoute,
}

const ApiSessionsCodeRouteWithChildren = ApiSessionsCodeRoute._addFileChildren(
  ApiSessionsCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiCompleteRoute: ApiCompleteRoute,
  ApiCheckpointsIdRoute: ApiCheckpointsIdRoute,
  ApiCompletionsTeamIdRoute: ApiCompletionsTeamIdRoute,
  ApiReportSessionIdRoute: ApiReportSessionIdRoute,
  ApiSessionsCodeRoute: ApiSessionsCodeRouteWithChildren,
  ApiCheckpointsIndexRoute: ApiCheckpointsIndexRoute,
  ApiHintIndexRoute: ApiHintIndexRoute,
  ApiSessionsIndexRoute: ApiSessionsIndexRoute,
  ApiCheckpointsSessionSessionIdRoute: ApiCheckpointsSessionSessionIdRoute,
  ApiSessionsIdQrRoute: ApiSessionsIdQrRoute,
  ApiSessionsIdStatusRoute: ApiSessionsIdStatusRoute,
  ApiSessionsIdIdRoute: ApiSessionsIdIdRoute,
  ApiTaskCheckpointIdTeamIdRoute: ApiTaskCheckpointIdTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
